name:                power-scheme-with-haskell
version:             0.1.0.0
github:              "githubuser/power-scheme-with-haskell"
license:             BSD3
author:              "Anthony Su"
maintainer:          "tonyfloater@gmail.com"
copyright:           "2018 Anthony SU"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/power-scheme-with-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && <= 3.1.13

library:
  source-dirs: src

executables:
  power-scheme-with-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - power-scheme-with-haskell

tests:
  power-scheme-with-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - power-scheme-with-haskell
